//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23msit013university.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFood
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cuisine { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public string isSpicy { get; set; }
    }
}
